### ISSUE TITLE
Missing bin_start_incl and bin_not_incl on point predictions leads to missing point values

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#1]
One of the submissions this week did not have the point predictions upload properly. Looking at the CSV, the `bin_start_incl` and `bin_end_notincl` values are blank, rather than `NA` as specified on the template. Could this be causing the point predictions to not upload? The CSV submitted is attached.

[failed_point_submission.zip](https://github.com/cdcepi/web_tracker/files/667092/failed_point_submission.zip)

**Comment by cdc-mgz4** [comment]
Yes, that is the cause for point predictions to not upload. I will be working on this.

**Comment by cdc-mgz4** [comment]
Is this the expected JSON result?
[result.zip](https://github.com/cdcepi/web_tracker/files/667304/result.zip)

**Comment by craigjmcgowan** [comment]
Yes, I believe that's correct

**Comment by cdc-mgz4** [comment]
Changes live
