### ISSUE TITLE
State submission JSON is cutting off mid-download

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#12]
I can download the national/regional JSON files without issue, but when downloading the state submissions for a week the download cuts off partway through, even though it indicates that it is finished. For example, the EW44 download should be ~42MB, but at most I am able to download 40MB before cutoff, usually around 20-25MB. This isn't an immediate priority but wanted to note it before I forgot.

**Comment by cdc-mgz4** [comment]
Please verify the data is complete or not. File sizes can me deceiving.

**Comment by craigjmcgowan** [comment]
It's definitely not complete. The JSON cuts off partway through.

**Comment by cdc-mgz4** [comment]
I've been working on a fix for this issue, almost done.

**Comment by cdc-mgz4** [comment]
Fix implemented but the issue as it turns out it not the code. Contacting our server providers to let them know request that take longer than 4min are being cut off without reason. I'm still going to make a final test by sending a huge file with the server to verify it's not a software issue.

**Comment by craigjmcgowan** [comment]
Ok - that makes sense with what I was seeing. Final file size was variable and would cut off at different places in the JSON, but it always gave me around 4 minutes, though I never timed in. Any idea why the connection is so slow that a 42MB file can't be downloaded in 4 min?

**Comment by cdc-mgz4** [comment]
They give us an average of 120kbytes per second or 1.2Mbps in service provider terms. I'm guessing there's a throttle at that speed to avoid VMs using too much bandwidth. What's unusual about this is the 4m rule, ISPs don't usually kill long running connections unless they are inactive for a long period of time.

**Comment by craigjmcgowan** [comment]
I was able to download some of the files this morning. The Nov 29 file worked immediately, the Nov 13 worked after several attempts, and I still haven't gotten the Nov 20 file yet.

**Comment by cdc-mgz4** [comment]
Speed improvements may have let you download the other weeks but that 20th of Nov is big which hits the cap. This still requires Phi lab intervention.

**Comment by cdc-mgz4** [comment]
moved to gitlab
