### ISSUE TITLE
State visualizations not vertically scaled

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#13]
Just putting this on here to have a record of it - seems like the visualizations are now pulling the data correctly for each week, but there's no vertical scale to the graph so everything ends up in a line on the bottom.

**Comment by cdc-mgz4** [comment]
new script is pulling observed data for states correcting this issue.

**Comment by craigjmcgowan** [comment]
This looks great! I've re-opened because there are still two states that are not rendering correctly - Louisiana and Mississippi. These states have elected not to publish their ILI data publically so those data aren't available to pull from online like the other states are. Is there a way to have the forecasts from these two states show up correctly, even though there won't be any observed truth to compare them against?

**Comment by cdc-mgz4** [comment]
Closing as this a separate issue albeit retailed. New Issue #16
