### ISSUE TITLE
week 45 ILINet data not updated

### ISSUE THREAD

**Issue by biggs1430** [cdcepi/web_tracker#14]
Week 45 ILINet data are not updating on the national and regional forecasting page even though they are posted on the FluView site.

**Comment by cdc-mgz4** [comment]
I've reset scheduled tasks to pull data every Saturday at 3am. Also set a duplicate to run every hour on Mondays for testing. If it works correctly I will set it to simply Mondays and Saturdays at 3am.

**Comment by cdc-mgz4** [comment]
New scheduled task word correctly. Closing
