### ISSUE TITLE
Error contacting the server when trying to upload csv forecast to website

### ISSUE THREAD

**Issue by carlosjarguello** [cdcepi/web_tracker#18]
**Description of problem**

Not possible to upload forecast csv file through the website.
Message displayed says: "Error contacting server... Please try again later".

**Steps to replicate**

Go to submission tab and select file to upload. After 2 minutes or so, 
error message appears.

I also tried uploading the original template file provided in the website to make sure it's not due to 
unexpected changes in said template when filling it with data. Error still occurs.

**Attaching screenshot below.**

![screen shot 2017-11-21 at 4 18 57 pm](https://user-images.githubusercontent.com/9260513/33097408-1b2cd4d0-ced8-11e7-8374-a1f8d59807c2.png)

**Comment by cdc-mgz4** [comment]
Please attach any files you tried submitting to the website.

**Comment by carlosjarguello** [comment]
Please see attached zip file (had to compress the files, github won't accept csv directly).
Thanks

[csv_files.zip](https://github.com/cdcepi/web_tracker/files/1496274/csv_files.zip)

**Comment by cdc-mgz4** [comment]
Thanks, I will let you know what I find when I have time to work on this project.

**Comment by cdc-mgz4** [comment]
I've tested your submission on both a development environment and a Test project that is not available to everyone at the production environment. In both cases your submission is uploaded successfully. Seems like the issue is on your end. 

What browser are you using? From your zip file I have a feeling you have a mac and in that case should not use safari to submit files. Currently it is recommended to use google chrome as it is the browser which has the best support.

**Comment by dinhlinh** [comment]
We have the same problems. Should I file a separate report?
<img width="1035" alt="screen shot 2017-11-29 at 9 35 29 pm" src="https://user-images.githubusercontent.com/13258043/33410300-9798eac4-d54d-11e7-80ef-1bbebed3965d.png">

**Comment by carlosjarguello** [comment]
Hi. My issue was solved by using google chrome instead of safari. Thanks.

**Comment by dinhlinh** [comment]
Thanks a bunch! I always used Safari. Maybe I have the same problem as you did.

**Comment by cdc-mgz4** [comment]
@carlosjarguello Good to hear your issue is solved. And thanks for replying back.

@dinhlinh Feel free to open a new issue if you still have problems submitting.
