### ISSUE TITLE
Team name pop-up when mousing over week-ahead forecasts

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#19]
Not sure how much work this would be, but if team names could pop up in bubble when mousing over the week ahead forecasts, similar to how they do when mousing over the peak forecasts, that would be helpful. Showing the numerical value of the forecast would be a plus but I think the team name alone would still be really helpful.

**Comment by cdc-mgz4** [comment]
That's the current behavior but you have to hover over the filled dots.

**Comment by craigjmcgowan** [comment]
Interesting - when I hover over the filled dots I see the confidence bands pop up but not the team names. I'm using Chrome on Windows 10
![untitled](https://user-images.githubusercontent.com/20864042/33376854-54dc77ca-d4dd-11e7-9a06-86e6c451dc29.png)

**Comment by cdc-mgz4** [comment]
My bad I remembered this feature a little better now. This was a feature of the original visualizations but at one point @majohansson told me to remove it. Can't remember why but that was a deliberate decision.

**Comment by cdc-mgz4** [comment]
Moved to gitlab
