### ISSUE TITLE
Forecast dates aren't displayed on admin side

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#2]
I just uploaded the next set of forecast dates for January, but none of the forecast dates are displayed on the admin side. I logged in with my user account and can see the future submission dates there, but nothing shows up on the admin side no matter what month I click on (see screenshot). 
![forecast_nodisplay](https://cloud.githubusercontent.com/assets/20864042/21523482/be00cd6e-ccdc-11e6-9f99-4a42f0b70f81.jpg)

Also, thanks for adding the month by month functionality - that will be super helpful.

**Comment by cdc-mgz4** [comment]
Fix is live
