### ISSUE TITLE
State Visualizer Typo in State Names - Massachusetts

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#20]
In the list of state names, "Massachusetts" is currently misspelled as "Massachetts" and no data are being displayed

**Comment by cdc-mgz4** [comment]
There's no code with state names and such that I can recall (will check later). If anything this could be the template having a typo or a user submitted file which could mean the validation is letting it slip.

**Comment by craigjmcgowan** [comment]
I double checked all of the template CSVs I've uploaded and it's spelled correctly on all of them. Maybe it's a user-submitted file

**Comment by cdc-mgz4** [comment]
Moved to gitlab
