### ISSUE TITLE
Priority list of locations should appear first in selection dropdown

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#21]
Is there a way to reorder which plot displays by default in the visualizations? For hospitalizations, I want "Overall" to be the default, followed by the age groups in order.

**Comment by cdc-mgz4** [comment]
Do you mean order in the legend?

**Comment by craigjmcgowan** [comment]
I'm referring to the order in the drop-down menu that controls which plot is being displayed, not the order of the teams (I know you've added a way to control those). Sorry if that was unclear

**Comment by cdc-mgz4** [comment]
There's no way to control that in the system right now. Completely possible of course add the feature in.

**Comment by craigjmcgowan** [comment]
Ok, thanks for clarifying. I think that would be a good feature to add at some point going forwards.

**Comment by cdc-mgz4** [comment]
Moved to gitlab
