### ISSUE TITLE
Add observed FluSurv-NET hospitalization data

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#24]
For the hospitalization visualizations, observed data needs to be added, similar to observed ILINet. Data can be accessed using https://gis.cdc.gov/GRASP/Fluview/FluHospRates.html. I've attached a zip file with the R function to pull the data as well as a CSV containing the results if you run
 `hospitalizations(surveillance_area = "flusurv", region = "all, year = 2017)`.

For the plots, we would want to use `year_wk_num` for the x-axis, `weeklyrate` for the observed value on the y-axis, and the plots are grouped by `age_label`. I believe I've correctly input the age labels as the "locations" for the plots so they should match the `age_label` values exactly.  

Let me know if you have any questions or if I can help more.

[hospital.zip](https://github.com/cdcepi/web_tracker/files/1535350/hospital.zip)

**Comment by cdc-mgz4** [comment]
I have a working version on my local computer. Seems like all `weeklyrate` values are one of 0.1, 0.2 or 0.3 Is this correct? 
I've pasted the output from the API, please disregard the label. WeightedILI might as well be called value at this point.
<details>
  <summary>Output</summary>
  [
  {
    "year": 2017,
    "week": 40,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 40,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 40,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 40,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 41,
    "weightedILI": 0
  },
  {
    "year": 2017,
    "week": 41,
    "weightedILI": 0
  },
  {
    "year": 2017,
    "week": 41,
    "weightedILI": 0
  },
  {
    "year": 2017,
    "week": 41,
    "weightedILI": 0
  },
  {
    "year": 2017,
    "week": 42,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 42,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 42,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 42,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 43,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 43,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 43,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 43,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 44,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 44,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 44,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 44,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 45,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 45,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 45,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 45,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 46,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 46,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 46,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 46,
    "weightedILI": 0.2
  },
  {
    "year": 2017,
    "week": 47,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 47,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 47,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 47,
    "weightedILI": 0.1
  },
  {
    "year": 2017,
    "week": 48,
    "weightedILI": 0.3
  },
  {
    "year": 2017,
    "week": 48,
    "weightedILI": 0.3
  },
  {
    "year": 2017,
    "week": 48,
    "weightedILI": 0.3
  },
  {
    "year": 2017,
    "week": 48,
    "weightedILI": 0.3
  }
]
</details>

**Comment by craigjmcgowan** [comment]
Those appear to be the observed weekly rates for the 18-49 yr age group, but I don't see the rates for the other age groups. I'm not sure why each value is showing up 4 times - I'm seeing the same effect when I pull the data through R or download the CSV via the FluView website. Let me check with the surveillance team here to see why that might be.

**Comment by cdc-mgz4** [comment]
Good guess! I should have stated that the data is for the 18-49 yr age group. Kept it to just one age group for brevity.

**Comment by craigjmcgowan** [comment]
Haha I had to check the website. Either way those numbers look valid for that group, but I'm not sure why each is replicated 4 times...

**Comment by cdc-mgz4** [comment]
Let me know, it could somehow make sense for them to repeat values. In that case I could just remove duplicates before storing them to the database.

**Comment by craigjmcgowan** [comment]
Surveillance is escalating the issue to their IT people. You're safe to remove duplicates if you want to move forward with that, I'm not sure on the ETA for a fix on the API side.

**Comment by craigjmcgowan** [comment]
Well apparently it wasn't too hard, since the fix is up now.

**Comment by cdc-mgz4** [comment]
Perfect I simply moved to work on #23 while this got solved. Continuing to work on this tomorrow.

**Comment by cdc-mgz4** [comment]
This now done, I will update the server. @craigjmcgowan I will open an issue for usability test of the new features.
