### ISSUE TITLE
Testing support for hospitalization data

### ISSUE THREAD

**Issue by cdc-mgz4** [cdcepi/web_tracker#26]
@craigjmcgowan Changes are live. Please do your own testing and le me know how it goes.

**Comment by craigjmcgowan** [comment]
Thanks! When I click on the "Forecasts" tab I see the visualizations flash on screen and then disappear. This is consistent across all three challenges and in both Chrome and Edge browsers. Could something be unintentionally causing them to disappear?

**Comment by cdc-mgz4** [comment]
No this is expected behaviour when there's an error. Don't show if broken. It should be working now. There is a big version gap between the database in server which can't be easily upgraded. I had to change the new code to be backwards compatible.

**Comment by craigjmcgowan** [comment]
Ok, that's good to know. State and National forecasts are now showing correctly again, but hospitalization forecasts are still disappearing for me.

**Comment by cdc-mgz4** [comment]
Can you attach a copy the template you are using? I will have a look at the error.

**Comment by craigjmcgowan** [comment]
Here's the template I used to set up the project.

[Hosp_Submission_Website_MonthOne.zip](https://github.com/cdcepi/web_tracker/files/1560714/Hosp_Submission_Website_MonthOne.zip)

**Comment by cdc-mgz4** [comment]
Moved to gitlab
