### ISSUE TITLE
Problem with uploading flu predictions to cdcepi website

### ISSUE THREAD

**Issue by sauravcsvt** [cdcepi/web_tracker#3]
Hello,

This is Saurav from Team 4Sight. I am trying to upload the flu predictions to the CDCEPI website. Given below are the sample errors that I am getting while uploading every week.
[EW3-4Sight-2017-01-30.zip](https://github.com/cdcepi/web_tracker/files/741102/EW3-4Sight-2017-01-30.zip)

**Target Season peak percentage, Location US National pair invalid.**

A Bin upper or lower bound does not match Project setup.

**Target 1 wk ahead, Location US National pair invalid.**

A Bin upper or lower bound does not match Project setup.

**Target 2 wk ahead, Location US National pair invalid.**

A Bin upper or lower bound does not match Project setup.

**Target 3 wk ahead, Location US National pair invalid.**

A Bin upper or lower bound does not match Project setup.

**Target 4 wk ahead, Location US National pair invalid.

**

A Bin upper or lower bound does not match Project setup.

**Comment by cdc-mgz4** [comment]
Upon deeper inspection your submission is not valid. This is not a bug or an issue on our end but something you need to address about your submission. Please note that the last bin in our templates, for example of US National, Season peak percentage has a bin_end_notincl of 100 while yours is NA.

Once corrected your submission should pass our validations.
