### ISSUE TITLE
Can't add baselines to 2017/18 project visualization page

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#4]
I'm setting up the 17/18 project page, and have no options to add baselines for the forecast visualizations. I'm using Chrome Version 61.0.3163.100

![baseline_error](https://user-images.githubusercontent.com/20864042/31392904-6820b2d0-ada8-11e7-8529-8e7375ce083c.png)

**Comment by cdc-mgz4** [comment]
When I enter the project edit page it shows the baselines.
![image](https://user-images.githubusercontent.com/18738022/31393507-dfffb886-ada9-11e7-8659-b28aa5fcd321.png)

Refresh and let me know if you see them.

**Comment by craigjmcgowan** [comment]
I'm on a different project - the FluSight 2017-18 project, which will contain the national and regional forecasts. It hasn't been published yet, could that be the issue?

**Comment by cdc-mgz4** [comment]
Commit https://github.com/cdcepi/epi_dev/commit/ba9c3dd476a7b466a97d7b8258b2705c7107ef9a should have fixed the issue. Hold on while I update the server.

**Comment by cdc-mgz4** [comment]
Server updated. Feel free to comment on this issue again if you encounter this bug again.
