### ISSUE TITLE
Not seeing submission options

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#5]
I've finally uploaded submission templates for the retrospective hospitalization project. I set the due date manually to November 2, 2017. However, when I log in to my user account to submit the historical average forecasts, I don't see any available forecast to submit to. I also tried changing the due date to tomorrow (Oct 17) but still do not see anything (see screenshot below)

![no_submission](https://user-images.githubusercontent.com/20864042/31618662-8aec57f8-b260-11e7-8a18-4b92db20e27a.png)

**Comment by cdc-mgz4** [comment]
Did you mark this section as a submit section?

**Comment by craigjmcgowan** [comment]
Thanks for catching that. I hadn't but even now that I have I still don't see anything. I also clicked "Future submissions" but still nothing

![no_submission](https://user-images.githubusercontent.com/20864042/31619234-e63392ba-b261-11e7-821a-15808a3fd044.png)

**Comment by cdc-mgz4** [comment]
I'm not able to update the server at this time. I will let you know when this is fixed.

**Comment by cdc-mgz4** [comment]
Server update is up. Please let me know if this is solved so I may close the issue.

**Comment by craigjmcgowan** [comment]
Doesn't seem to be fixed yet. Tried deleting the existing submission dates and re-uploading, but still not able to see any options to submit as a user

![no_submission](https://user-images.githubusercontent.com/20864042/31901140-98d67e82-b7ee-11e7-9909-d60ce4f8e340.png)

**Comment by cdc-mgz4** [comment]
Please verify again, although these uploads don't appear to have locations. Is that correct?

**Comment by craigjmcgowan** [comment]
I now see the option to submit, but when I submit a file I get an unable to parse CSV message. The hospitalization forecasts are a slightly different structure. The location column is replaced by "age_grp" and the targets are slightly different. There are still the 1-4 week ahead targets as well as season peak week, but season peak percentage is replaced by season peak rate and season onset is dropped.

**Comment by cdc-mgz4** [comment]
Modifying the templates like changing a column name is not supported. The new column is not saved nor validated by the system and the visualizations are likely not going to work. Dropping, adding more or less target or locations is fine but calling them something different is not going to work right now. 

Please send me this new template.

**Comment by craigjmcgowan** [comment]
Ok. I've emailed you the new template - there's only one column with a different label. If I'm understanding you correctly, if I change the label of the "age_grp" column to "location" then we should be ok, since the different values in those columns are still allowed?

**Comment by cdc-mgz4** [comment]
Your template doesn't include a Point typed row for Overall, Season peak week. That is required even if they are not going to provide a point prediction for this Target, Age Group. After that there should be no issue collecting data.

To visualize it we only have one issue, there no defined way to visualize the new target, Season peak rate.
Basically the new target would be ignored while others are visualized correctly.

@majohansson RFC (request for comment)

**Comment by craigjmcgowan** [comment]
Ok, I've added that row. It would be great if the website could handle the 'age_grp' label column so that the submission template accurately reflects what is being forecast

**Comment by cdc-mgz4** [comment]
Moving feature request to Gitlab
