### ISSUE TITLE
Interactive visualizations are stuck on week 41

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#7]
Sorry to add another issue, but the interactive visualizations only have observed ILI values up to week 41 (week 43 is currently published) and the view defaults to showing that week, which means users have to click in order to see the forecasts submitted during week 44.

Can we have the visualizations default to showing the most recent forecasts received? The forecasts themselves are rendering great once the correct week is selected.

**Comment by cdc-mgz4** [comment]
I will look into this, that's how it's supposed to work.

**Comment by craigjmcgowan** [comment]
Related to this - forecasts are based off of the last week of observed data, not the date that they were received. Using the forecasts due Nov 6 as an example, the most recent data released was for Week 43. The 1 wk forecasts are therefore for week 44, 2 wk for 45, etc. 

However, Nov 6 is during week 45 and the visualizations seems to be using the week received as the reference, displaying the 1 wk forecasts for week 46, 2 week for 47, etc. These should be shifted backwards two weeks to be accurately displaying what is being forecast. Let me know if that's not clear or you have any other questions and thanks!

**Comment by cdc-mgz4** [comment]
They are now stuck on 42, the observed line data for 2017 is delayed which is causing this bug.

**Comment by craigjmcgowan** [comment]
As I mentioned in my email, could this also be a result of FluView Interactive's switch to HTML5? I'm not sure how long they're going to maintain the Flash portal or if it's being updated as frequently.

**Comment by cdc-mgz4** [comment]
Is their HTML5 portal up to date? It seem like they either stopped updating the old Flash based portal or is in transition.

It would be helpful to find where we can pull the observed data from the website.

**Comment by craigjmcgowan** [comment]
Yes, the HTML5 portal is up to date and is how they'll be distributing it going forwards. The tool is here: https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html and you can download just ILINet automatically through https://gis.cdc.gov/grasp/flu2/PostPhase02DataDownload with a JSON of download parameters

**Comment by cdc-mgz4** [comment]
New script is pulling the data correctly now, state data will be up in a few.
