### ISSUE TITLE
Uploading CSV Issue - no indication that it worked or it failed

### ISSUE THREAD

**Issue by JeffMorgan** [cdcepi/web_tracker#9]
I have tried to upload my CSV (Excel file) about a dozen times today.  It appears to be uploading as I get a "Processing" message, but then it stops without indicating whether it was successful.  The field is blank and the Past Submitted folder states that I don't have any past submittals.

**Comment by cdc-mgz4** [comment]
Please attach your CSV, normal behavior is to validate your file and give back error messages to assist you in fixing it to pass validation. Note that the Excel file format is not accepted. Your file should be able to open with a basic text editor like notepad, if not then you will have to format it in CSV and resubmit.

**Comment by cdc-mgz4** [comment]
Closing due to lack of response. Feel free to reopen if you still need help.
